apiVersion: v1
kind: Namespace
metadata:
  name: fenwave
  labels:
    name: fenwave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fenwave-idp
  namespace: fenwave
  labels:
    app: fenwave-idp
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fenwave-idp
  template:
    metadata:
      labels:
        app: fenwave-idp
    spec:
      serviceAccountName: fenwave-idp
      containers:
      - name: fenwave-idp
        image: 954976325487.dkr.ecr.eu-west-1.amazonaws.com/eks-infrastructure/idp:v8
        ports:
        - containerPort: 7007
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_CONFIG_app_baseUrl
          value: "https://fenwave.your-domain.com"
        - name: APP_CONFIG_backend_baseUrl
          value: "https://fenwave.your-domain.com"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        volumeMounts:
        - name: app-config
          mountPath: /app/app-config.production.yaml
          subPath: app-config.production.yaml
          readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: fenwave-config
---
apiVersion: v1
kind: Service
metadata:
  name: fenwave-idp-service
  namespace: fenwave
  labels:
    app: fenwave-idp
spec:
  selector:
    app: fenwave-idp
  ports:
  - name: http
    port: 80
    targetPort: 7007
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fenwave-idp
  namespace: fenwave
  labels:
    app: fenwave-idp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fenwave-config
  namespace: fenwave
data:
  app-config.production.yaml: |
    app:
      title: Fenwave IDP
      baseUrl: https://fenwave.your-domain.com

    backend:
      baseUrl: https://fenwave.your-domain.com
      listen:
        port: 7007
        host: 0.0.0.0
      database:
        client: pg
        connection:
          host: postgres-service
          port: 5432
          user: backstage
          password: backstage123
          database: backstage

    # Basic integrations only (no custom ArgoCD plugins for now)
    integrations:
      github:
        - host: github.com
          # token: ${GITHUB_TOKEN}  # Add when needed

    auth:
      environment: production
      providers:
        guest: {}

    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location]

    techdocs:
      builder: 'local'
      generator:
        runIn: 'local'
      publisher:
        type: 'local'

    scaffolder:
      defaultAuthor:
        name: Fenwave
        email: admin@fenwave.com
      defaultCommitMessage: 'Initial commit'