apiVersion: v1
kind: Service
metadata:
  name: fenwave-idp-service
  namespace: fenwave
  labels:
    app: fenwave-idp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 7007
      protocol: TCP
      name: http
  selector:
    app: fenwave-idp
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: fenwave
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres