apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesStrategicMerge:
- deployment-prod.yaml

images:
- name: 954976325487.dkr.ecr.eu-west-1.amazonaws.com/fenwave/idp
  newTag: v3