name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'

env:
  TF_VERSION: '1.9.8'  # Updated to support S3 native locking
  AWS_REGION: 'eu-west-1'

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [dev]
        
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: terraform-plan-${{ matrix.environment }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      working-directory: terraform
      run: |
        terraform init \
          -backend-config="environments/${{ matrix.environment }}/backend.conf" \
          -input=false
      env:
        TF_VAR_environment: ${{ matrix.environment }}

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: |
        terraform plan \
          -var-file="environments/${{ matrix.environment }}/terraform.tfvars" \
          -out=tfplan-${{ matrix.environment }} \
          -input=false
      env:
        TF_VAR_environment: ${{ matrix.environment }}

    - name: Save Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ matrix.environment }}
        path: terraform/tfplan-${{ matrix.environment }}
        retention-days: 5

    - name: Create Plan Summary
      working-directory: terraform
      run: |
        echo "## Terraform Plan Summary for ${{ matrix.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        terraform show -no-color tfplan-${{ matrix.environment }} | head -50 >> $GITHUB_STEP_SUMMARY

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const { execSync } = require('child_process');
          
          try {
            const plan = execSync('cd terraform && terraform show -no-color tfplan-${{ matrix.environment }}', 
              { encoding: 'utf-8', maxBuffer: 1024 * 1024 });
            
            const output = `
            ## Terraform Plan Results for \`${{ matrix.environment }}\`
            
            <details>
            <summary>Show Plan</summary>
            
            \`\`\`
            ${plan.slice(0, 10000)}${plan.length > 10000 ? '\n\n... (truncated)' : ''}
            \`\`\`
            
            </details>
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
          } catch (error) {
            console.error('Error creating comment:', error);
          }